version: '3.8'

services:
  chromadb:
    image: chromadb/chroma:latest
    container_name: aym_chromadb
    command: --reload --workers 1 --host 0.0.0.0 --port 8000
    environment:
      - IS_PERSISTENT=TRUE
      - ALLOW_RESET=TRUE
    ports:
      - 8000:8000
    volumes:
      - index_data:/index_data  
    restart: unless-stopped  

volumes:
  index_data:
    driver: local  
